# Fleet Configuration - Super Simple!
# Just fill in your services below

project = "my-app"

# Add your services here
[[services]]
name = "website"
image = "nginx"
port = 80
folder = "./my-website"  # Put your HTML files here

[[services]]
name = "database"
image = "postgres"
port = 5432
password = "changeme"  # Don't forget to change this!

# Want to add more services? Just copy the pattern above!