# Development environment with cache (no passwords)
project = "dev-app"

# Simple Redis setup without password for local development
[[services]]
name = "app"
image = "node:20"
port = 3000
folder = "app"
cache = "redis"  # Uses default Redis 7.2 without password
environment = { NODE_ENV = "development" }
command = "npm run dev"

# Service using default Memcached
[[services]]
name = "session-store"
image = "python:3.11"
port = 5000
folder = "sessions"
cache = "memcached"  # Uses default Memcached 1.6
cache_max_memory = "64m"
command = "python server.py"

# Multiple services sharing same Redis
[[services]]
name = "worker1"
image = "python:3.11"
folder = "workers"
cache = "redis"  # Shares Redis with app service
command = "python worker1.py"

[[services]]
name = "worker2"
image = "python:3.11"
folder = "workers"
cache = "redis"  # Shares Redis with app and worker1
command = "python worker2.py"