# Multiple services sharing single Mailpit instance
project = "multi-email"

# All services will share a single Mailpit instance
# regardless of version specified (singleton pattern)

[[services]]
name = "frontend"
image = "node:20"
port = 3000
folder = "frontend"
email = "mailpit:1.20"
command = "npm run dev"

[[services]]
name = "backend"
image = "python:3.11"
port = 8000
folder = "backend"
email = "mailpit:1.19"  # Different version but same instance
command = "python manage.py runserver"

[[services]]
name = "notification-service"
image = "golang:1.21"
port = 9000
folder = "notifications"
email = "mailpit"  # No version specified
command = "go run main.go"

[[services]]
name = "cron-jobs"
image = "alpine:3.19"
folder = "cron"
email = "mailpit:latest"  # Latest version but still same instance
command = "crond -f"