# Laravel application with MySQL database
project = "laravel-app"

[[services]]
name = "app"
image = "nginx:alpine"
port = 80
domain = "laravel.test"
runtime = "php:8.2"
framework = "laravel"  # Optional - auto-detected if artisan file exists
folder = "./laravel"
[services.env]
APP_ENV = "local"
APP_DEBUG = "true"
APP_KEY = "base64:YOUR_KEY_HERE"
DB_CONNECTION = "mysql"
DB_HOST = "database"
DB_PORT = "3306"
DB_DATABASE = "laravel"
DB_USERNAME = "laravel"
DB_PASSWORD = "secret"

[[services]]
name = "database"
image = "mysql:8.0"
port = 3306
password = "secret"
[services.env]
MYSQL_DATABASE = "laravel"
MYSQL_USER = "laravel"
MYSQL_PASSWORD = "secret"
volumes = ["db-data:/var/lib/mysql"]

[[services]]
name = "redis"
image = "redis:alpine"
port = 6379